spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to Prod Environment - Bank Cards's related queries"
  contactDetails:
    name: "John Smith"
    email: "cardssupport@bank.com"
    phone: "1234567890"
  onCallSupport:
    - "2345678901"
    - "3456789012"
