spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"


cards:
  message: "Welcome to QA Environment - Bank Cards's related queries"
  contactDetails:
    name: "Aditya Bansal"
    email: "cardsupport@mybank.com"
    phone: "9876123456"
  onCallSupport:
    - "9812345678"
    - "9887654321"